CREATE TABLE "AssetHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TotalBalance" numeric(18,2) NOT NULL,
    "ProfitLoss" numeric(18,2) NOT NULL,
    "RecordedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssetHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssetHistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);
