CREATE TABLE "ScrapingLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Status" integer NOT NULL,
    "Message" text,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone,
    CONSTRAINT "PK_ScrapingLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScrapingLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ScrapingLogs_UserId" ON "ScrapingLogs" ("UserId");
